//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Data.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyTexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod.Data.Localization.MyTexts", typeof(MyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [option] Disables an option ähnelt.
        /// </summary>
        internal static string Description_SS_Disable {
            get {
                return ResourceManager.GetString("Description_SS_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [option] Enables an option ähnelt.
        /// </summary>
        internal static string Description_SS_Enable {
            get {
                return ResourceManager.GetString("Description_SS_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows a help page ähnelt.
        /// </summary>
        internal static string Description_SS_Help {
            get {
                return ResourceManager.GetString("Description_SS_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists all options ähnelt.
        /// </summary>
        internal static string Description_SS_List {
            get {
                return ResourceManager.GetString("Description_SS_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [option] [value] Set an option to value. ähnelt.
        /// </summary>
        internal static string Description_SS_Set {
            get {
                return ResourceManager.GetString("Description_SS_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong arguments. Expect [option] [value] arguments. ähnelt.
        /// </summary>
        internal static string Error_SS_Argument {
            get {
                return ResourceManager.GetString("Error_SS_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not convert &apos;{0}&apos; to {1}. ähnelt.
        /// </summary>
        internal static string Error_SS_Convert {
            get {
                return ResourceManager.GetString("Error_SS_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not have permission to set this option. ähnelt.
        /// </summary>
        internal static string Error_SS_NoPermission {
            get {
                return ResourceManager.GetString("Error_SS_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Boolean options can be used. ähnelt.
        /// </summary>
        internal static string Error_SS_OnlyBooleanAllowed {
            get {
                return ResourceManager.GetString("Error_SS_OnlyBooleanAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to set {0} to {1}. ähnelt.
        /// </summary>
        internal static string Error_SS_SetOption {
            get {
                return ResourceManager.GetString("Error_SS_SetOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown option &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Error_SS_UnknownOption {
            get {
                return ResourceManager.GetString("Error_SS_UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} successfully set to {1}. ähnelt.
        /// </summary>
        internal static string Message_SS_SetOptionSuccess {
            get {
                return ResourceManager.GetString("Message_SS_SetOptionSuccess", resourceCulture);
            }
        }
    }
}
